language: java

services:
  - docker

sudo: required
git:
  depth: 3

install:
  - git clone https://github.com/FAForever/db.git
  - docker build -t faf-db db
  - docker run -d -p 3306 faf-db

script:
  - chmod +x gradlew && ./gradlew build

after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then
      ./gradlew jacocoTestReport coveralls pushDockerImage;
    fi
