language: java

services:
  - docker

sudo: required
git:
  depth: 3

before_install:
  - sudo /etc/init.d/mysql stop
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.10.0/docker-compose-`uname -s`-`uname -m` > /tmp/docker-compose
  - chmod +x /tmp/docker-compose
  - sudo mv /tmp/docker-compose /usr/local/bin

install:
  - git clone https://github.com/FAForever/faf-stack.git
  - docker-compose -f faf-stack/docker-compose.yml up -d faf-db

script:
  - chmod +x gradlew && ./gradlew build --info

after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then
      ./gradlew jacocoTestReport coveralls pushDockerImage;
    fi
