faf-api:
  jwt-secret: ${JWT_SECRET}
  map:
    folder-zip-files: ${MAP_UPLOAD_PATH}
    folder-preview-path-small: ${MAP_PREVIEW_PATH_SMALL}
    folder-preview-path-large: ${MAP_PREVIEW_PATH_LARGE}
  git-hub:
    access-token: ${GITHUB_ACCESS_TOKEN}
    deployment-environment: ${GITHUB_DEPLOYMENT_ENVIRONMENT:production}
    repositories-directory: ${REPOSITORY_DIRECTORY}
    webhook-secret: ${GITHUB_WEBHOOK_SECRET}
  deployment:
    forged-alliance-exe-path: ${FORGED_ALLIANCE_EXE_PATH}
    repositories-folder: ${REPOSITORIES_FOLDER}
    target-folder: ${DEPLOYMENT_TARGET_FOLDER}
    configurations:
      - repositoryUrl: https://github.com/FAForever/fa.git
        branch: deploy/faf
        modName: faf
        modFilesExtension: .nx2
        replaceExisting: false
      - repositoryUrl: https://github.com/FAForever/fa.git
        branch: deploy/fafbeta
        modName: fafbeta
        modFilesExtension: .nx4
        replaceExisting: true
      - repositoryUrl: https://github.com/FAForever/fa.git
        branch: deploy/fafdevelop
        modName: fafdevelop
        modFilesExtension: .nx5
        replaceExisting: true

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS}/${DATABASE_NAME}?useSSL=false
    name: faf
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
