faf-api:
  jwt-secret: ${JWT_SECRET:banana}
  map:
    folder-zip-files: ${MAP_UPLOAD_PATH:build/cache/map/maps}
    folder-preview-path-small: ${MAP_PREVIEW_PATH_SMALL:build/cache/map_previews/small}
    folder-preview-path-large: ${MAP_PREVIEW_PATH_LARGE:build/cache/map_previews/large}
  git-hub:
    access-token: ${GITHUB_ACCESS_TOKEN:none}
    deployment-environment: ${GITHUB_DEPLOYMENT_ENVIRONMENT:development}
    repositories-directory: ${REPOSITORIES_DIRECTORY:build/cache/repos}
    webhook-secret: ${GITHUB_WEBHOOK_SECRET:none}
  deployment:
    forged-alliance-exe-path: ${FORGED_ALLIANCE_EXE_PATH}
    repositories-folder: ${REPOSITORIES_FOLDER:build/cache/repos}
    target-folder: ${DEPLOYMENT_TARGET_FOLDER:build/cache/deployment}

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS:localhost}/${DATABASE_NAME:faf}?useSSL=false
    name: faf
    username: ${DATABASE_USERNAME:faf-api}
    password: ${DATABASE_PASSWORD:banana}
  jpa:
    show-sql: true

logging:
  level:
    com.faforever.api: trace
