faf-api:
  jwt-secret: banana

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS:localhost}/${DATABASE_NAME:faf}?useSSL=false
    name: faf
    username: ${DATABASE_USERNAME:faf-api}
    password: ${DATABASE_PASSWORD:banana}
  jpa:
    show-sql: true
