faf-api:
  jwt-secret: banana

spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/faf_lobby?useSSL=false
    name: faf_lobby
    username: root
    password: banana
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
